import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddPermissions1729413716921 implements MigrationInterface {
  name = 'AddPermissions1729413716921';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
			INSERT INTO permissions (permission_id, name, description) VALUES
			(1, 'CREATE_ROLE_PERMISSION', 'Permission to create roles'),
			(2, 'READ_ROLE_PERMISSION', 'Permission to read roles'),
			(3, 'UPDATE_ROLE_PERMISSION', 'Permission to update roles'),
			(4, 'DELETE_ROLE_PERMISSION', 'Permission to delete roles'),
			(5, 'READ_PERMISSION_PERMISSION', 'Permission to read permissions'),
			(6, 'UPDATE_PERMISSION_PERMISSION', 'Permission to update permissions'),
			(7, 'CREATE_SCHOOL_YEAR_PERMISSION', 'Permission to create school years'),
			(8, 'READ_ALL_SCHOOL_YEAR_PERMISSION', 'Permission to read all school years'),
			(9, 'UPDATE_SCHOOL_YEAR_PERMISSION', 'Permission to update school years'),
			(10, 'DELETE_SCHOOL_YEAR_PERMISSION', 'Permission to delete school years'),
			(11, 'CREATE_STUDENT_PERMISSION', 'Permission to create students'),
			(12, 'READ_ALL_STUDENT_PERMISSION', 'Permission to read all students'),
			(13, 'UPDATE_STUDENT_PERMISSION', 'Permission to update students'),
			(14, 'DELETE_STUDENT_PERMISSION', 'Permission to delete students'),
			(15, 'CREATE_PARENT_PERMISSION', 'Permission to create parents'),
			(16, 'READ_ALL_PARENT_PERMISSION', 'Permission to read all parents'),
			(17, 'UPDATE_PARENT_PERMISSION', 'Permission to update parents'),
			(18, 'DELETE_PARENT_PERMISSION', 'Permission to delete parents'),
			(19, 'CREATE_SCHOOL_FACULTY_PERMISSION', 'Permission to create school faculties'),
			(20, 'READ_SCHOOL_FACULTY_PERMISSION', 'Permission to read school faculties'),
			(21, 'UPDATE_SCHOOL_FACULTY_PERMISSION', 'Permission to update school faculties'),
			(22, 'DELETE_SCHOOL_FACULTY_PERMISSION', 'Permission to delete school faculties'),
			(23, 'CREATE_CLASS_PERMISSION', 'Permission to create classes'),
			(24, 'READ_ALL_CLASS_PERMISSION', 'Permission to read all classes'),
			(25, 'UPDATE_CLASS_PERMISSION', 'Permission to update classes'),
			(26, 'DELETE_CLASS_PERMISSION', 'Permission to delete classes'),
			(27, 'READ_ASSIGNED_CLASS_PERMISSION', 'Permission to read assigned classes'),
			(28, 'UPDATE_ASSIGNED_CLASS_PERMISSION', 'Permission to update assigned classes'),
			(29, 'DELETE_ASSIGNED_CLASS_PERMISSION', 'Permission to delete assigned classes'),
			(30, 'ADD_CLASS_STUDENT_PERMISSION', 'Permission to add students to classes'),
			(31, 'UPDATE_CLASS_STUDENT_PERMISSION', 'Permission to update class students'),
			(32, 'REMOVE_CLASS_STUDENT_PERMISSION', 'Permission to remove students from classes'),
			(33, 'ADD_ASSIGNED_CLASS_STUDENT_PERMISSION', 'Permission to add students to assigned classes'),
			(34, 'READ_ASSIGNED_CLASS_STUDENT_PERMISSION', 'Permission to read assigned class students'),
			(35, 'UPDATE_ASSIGNED_CLASS_STUDENT_PERMISSION', 'Permission to update assigned class students'),
			(36, 'REMOVE_ASSIGNED_CLASS_STUDENT_PERMISSION', 'Permission to remove students from assigned classes'),
			(37, 'CREATE_ASSIGNED_CLASS_SCHEDULE_PERMISSION', 'Permission to create assigned class schedules'),
			(38, 'READ_ASSIGNED_CLASS_SCHEDULE_PERMISSION', 'Permission to read assigned class schedules'),
			(39, 'UPDATE_ASSIGNED_CLASS_SCHEDULE_PERMISSION', 'Permission to update assigned class schedules'),
			(40, 'DELETE_ASSIGNED_CLASS_SCHEDULE_PERMISSION', 'Permission to delete assigned class schedules'),
			(41, 'CREATE_CLASS_SCHEDULE_PERMISSION', 'Permission to create class schedules'),
			(42, 'READ_CLASS_SCHEDULE_PERMISSION', 'Permission to read class schedules'),
			(43, 'UPDATE_CLASS_SCHEDULE_PERMISSION', 'Permission to update class schedules'),
			(44, 'DELETE_CLASS_SCHEDULE_PERMISSION', 'Permission to delete class schedules'),
			(45, 'CREATE_ASSIGNED_CLASS_MENU_PERMISSION', 'Permission to create assigned class menus'),
			(46, 'READ_ASSIGNED_CLASS_MENU_PERMISSION', 'Permission to read assigned class menus'),
			(47, 'UPDATE_ASSIGNED_CLASS_MENU_PERMISSION', 'Permission to update assigned class menus'),
			(48, 'DELETE_ASSIGNED_CLASS_MENU_PERMISSION', 'Permission to delete assigned class menus'),
			(49, 'CREATE_CLASS_MENU_PERMISSION', 'Permission to create class menus'),
			(50, 'READ_CLASS_MENU_PERMISSION', 'Permission to read class menus'),
			(51, 'UPDATE_CLASS_MENU_PERMISSION', 'Permission to update class menus'),
			(52, 'DELETE_CLASS_MENU_PERMISSION', 'Permission to delete class menus'),
			(53, 'READ_ASSIGNED_CLASS_LOA_PERMISSION', 'Permission to read assigned class leave of absence'),
			(54, 'UPDATE_ASSIGNED_CLASS_LOA_PERMISSION', 'Permission to update assigned class leave of absence'),
			(55, 'READ_LOA_PERMISSION', 'Permission to read leave of absence'),
			(56, 'UPDATE_LOA_PERMISSION', 'Permission to update leave of absence'),
			(57, 'CREATE_ALBUM_PERMISSION', 'Permission to create albums'),
			(58, 'READ_ALL_ALBUM_PERMISSION', 'Permission to read all albums'),
			(59, 'UPDATE_ALL_ALBUM_PERMISSION', 'Permission to update all albums'),
			(60, 'DELETE_ALL_ALBUM_PERMISSION', 'Permission to delete all albums'),
			(61, 'CREATE_ASSIGNED_CLASS_ALBUM_PERMISSION', 'Permission to create assigned class albums'),
			(62, 'READ_ASSIGNED_CLASS_ALBUM_PERMISSION', 'Permission to read assigned class albums'),
			(63, 'UPDATE_ASSIGNED_CLASS_ALBUM_PERMISSION', 'Permission to update assigned class albums'),
			(64, 'DELETE_ASSIGNED_CLASS_ALBUM_PERMISSION', 'Permission to delete assigned class albums'),
			(65, 'READ_SCHOOL_ASSETS_PERMISSION', 'Permission to read school assets'),
			(66, 'UPDATE_SCHOOL_PERMISSION', 'Permission to update school'),
			(67, 'CREATE_POST_PERMISSION', 'Permission to create posts'),
			(68, 'READ_ALL_POST_PERMISSION', 'Permission to read all posts'),
			(69, 'UPDATE_POST_PERMISSION', 'Permission to update posts'),
			(70, 'DELETE_POST_PERMISSION', 'Permission to delete posts'),
			(71, 'CREATE_ASSIGNED_CLASS_POST_PERMISSION', 'Permission to create assigned class posts'),
			(72, 'READ_ASSIGNED_CLASS_POST_PERMISSION', 'Permission to read assigned class posts'),
			(73, 'UPDATE_ASSIGNED_CLASS_POST_PERMISSION', 'Permission to update assigned class posts'),
			(74, 'DELETE_ASSIGNED_CLASS_POST_PERMISSION', 'Permission to delete assigned class posts'),
			(75, 'CREATE_COMMENT_PERMISSION', 'Permission to create comments'),
			(76, 'READ_ALL_COMMENT_PERMISSION', 'Permission to read all comments'),
			(77, 'UPDATE_COMMENT_PERMISSION', 'Permission to update comments'),
			(78, 'DELETE_COMMENT_PERMISSION', 'Permission to delete comments'),
			(79, 'CREATE_ASSIGNED_CLASS_POST_COMMENT_PERMISSION', 'Permission to create assigned class post comments'),
			(80, 'READ_ASSIGNED_CLASS_POST_COMMENT_PERMISSION', 'Permission to read assigned class post comments'),
			(81, 'UPDATE_ASSIGNED_CLASS_POST_COMMENT_PERMISSION', 'Permission to update assigned class post comments'),
			(82, 'DELETE_ASSIGNED_CLASS_POST_COMMENT_PERMISSION', 'Permission to delete assigned class post comments'),
			(83, 'READ_SCHOOL_NOTIFICATION_PERMISSION', 'Permission to read school notifications'),
			(84, 'CREATE_SCHOOL_NOTIFICATION_PERMISSION', 'Permission to create school notifications'),
			(85, 'READ_ASSIGNED_CLASS_NOTIFICATION_PERMISSION', 'Permission to read assigned class notifications'),
			(86, 'CREATE_ASSIGNED_CLASS_NOTIFICATION_PERMISSION', 'Permission to create assigned class notifications'),
			(87, 'READ_MEDICAL_PERMISSION', 'Permission to read medical information'),
			(88, 'READ_ASSIGNED_CLASS_MEDICAL_PERMISSION', 'Permission to read assigned class medical information'),
			(89, 'CREATE_SCHOOL_ALBUM_PERMISSION', 'Permission to create school albums'),
			(90, 'READ_SCHOOL_ALBUM_PERMISSION', 'Permission to read school albums'),
			(91, 'UPDATE_SCHOOL_ALBUM_PERMISSION', 'Permission to update school albums'),
			(92, 'DELETE_SCHOOL_ALBUM_PERMISSION', 'Permission to delete school albums'),
			(93, 'CREATE_SCHOOL_POST_PERMISSION', 'Permission to create school posts'),
			(94, 'READ_SCHOOL_POST_PERMISSION', 'Permission to read school posts'),
			(95, 'UPDATE_SCHOOL_POST_PERMISSION', 'Permission to update school posts'),
			(96, 'DELETE_SCHOOL_POST_PERMISSION', 'Permission to delete school posts'),
			(97, 'CREATE_SCHOOL_POST_COMMENT_PERMISSION', 'Permission to create school post comments'),
			(98, 'READ_SCHOOL_POST_COMMENT_PERMISSION', 'Permission to read school post comments'),
			(99, 'UPDATE_SCHOOL_POST_COMMENT_PERMISSION', 'Permission to update school post comments'),
			(100, 'DELETE_SCHOOL_POST_COMMENT_PERMISSION', 'Permission to delete school post comments');
		`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DELETE FROM permissions WHERE id BETWEEN 1 AND 100`,
    );
  }
}
