export const ROLE_PERMISSIONS = 1;
export const CREATE_ROLE_PERMISSION = 2;
export const READ_ROLE_PERMISSION = 3;
export const UPDATE_ROLE_PERMISSION = 4;
export const DELETE_ROLE_PERMISSION = 5;

export const PERMISSION_PERMISSIONS = 6;
export const READ_PERMISSION_PERMISSION = 7;
export const UPDATE_PERMISSION_PERMISSION = 8;

// School year permissions
export const SCHOOL_YEAR_PERMISSIONS = 9;
export const CREATE_SCHOOL_YEAR_PERMISSION = 10;
export const READ_ALL_SCHOOL_YEAR_PERMISSION = 11;
export const UPDATE_SCHOOL_YEAR_PERMISSION = 12;
export const DELETE_SCHOOL_YEAR_PERMISSION = 13;

// Student permissions
export const STUDENT_PERMISSIONS = 14;
export const CREATE_STUDENT_PERMISSION = 15;
export const READ_ALL_STUDENT_PERMISSION = 16;
export const UPDATE_STUDENT_PERMISSION = 17;
export const DELETE_STUDENT_PERMISSION = 18;

// Parent permissions
export const PARENT_PERMISSIONS = 19;
export const CREATE_PARENT_PERMISSION = 20;
export const READ_ALL_PARENT_PERMISSION = 21;
export const UPDATE_PARENT_PERMISSION = 22;
export const DELETE_PARENT_PERMISSION = 23;

// Teacher permissions
export const SCHOOL_FACULTY_PERMISSIONS = 24;
export const CREATE_SCHOOL_FACULTY_PERMISSION = 25;
export const READ_ALL_SCHOOL_FACULTY_PERMISSION = 26;
export const UPDATE_SCHOOL_FACULTY_PERMISSION = 27;
export const DELETE_SCHOOL_FACULTY_PERMISSION = 28;

// Class permissions
export const CLASS_PERMISSIONS = 29;
export const CREATE_CLASS_PERMISSION = 30;
export const READ_ALL_CLASS_PERMISSION = 31;
export const UPDATE_CLASS_PERMISSION = 32;
export const DELETE_CLASS_PERMISSION = 33;

export const ASSIGNED_CLASS_PERMISSIONS = 34;
export const READ_ASSIGNED_CLASS_PERMISSION = 35;
export const UPDATE_ASSIGNED_CLASS_PERMISSION = 36;
export const DELETE_ASSIGNED_CLASS_PERMISSION = 37;

// Class student permissions
export const CLASS_STUDENT_PERMISSIONS = 38;
export const ADD_CLASS_STUDENT_PERMISSION = 39;
export const UPDATE_CLASS_STUDENT_PERMISSION = 40;
export const REMOVE_CLASS_STUDENT_PERMISSION = 41;

export const ASSIGNED_CLASS_STUDENT_PERMISSIONS = 42;
export const ADD_ASSIGNED_CLASS_STUDENT_PERMISSION = 43;
export const READ_ASSIGNED_CLASS_STUDENT_PERMISSION = 44;
export const UPDATE_ASSIGNED_CLASS_STUDENT_PERMISSION = 45;
export const REMOVE_ASSIGNED_CLASS_STUDENT_PERMISSION = 46;

// Class faculty permissions
export const CLASS_FACULTY_PERMISSIONS = 47;
export const ADD_CLASS_FACULTY_PERMISSION = 48;
export const REMOVE_CLASS_FACULTY_PERMISSION = 49;

// Delete history permissions
export const CLASS_HISTORY_PERMISSIONS = 50;
export const DELETE_CLASS_HISTORY_PERMISSION = 51;
export const WORK_HISTORY_PERMISSIONS = 52;
export const DELETE_WORK_HISTORY_PERMISSION = 53;

// Class schedule permissions
export const CLASS_SCHEDULE_PERMISSIONS = 54;
export const CREATE_CLASS_SCHEDULE_PERMISSION = 55;
export const READ_ALL_CLASS_SCHEDULE_PERMISSION = 56;
export const UPDATE_CLASS_SCHEDULE_PERMISSION = 57;
export const DELETE_CLASS_SCHEDULE_PERMISSION = 58;

export const ASSIGNED_CLASS_SCHEDULE_PERMISSIONS = 59;
export const CREATE_ASSIGNED_CLASS_SCHEDULE_PERMISSION = 60;
export const READ_ASSIGNED_CLASS_SCHEDULE_PERMISSION = 61;
export const UPDATE_ASSIGNED_CLASS_SCHEDULE_PERMISSION = 62;
export const DELETE_ASSIGNED_CLASS_SCHEDULE_PERMISSION = 63;

// Assigned class menu permissions
export const CLASS_MENU_PERMISSIONS = 64;
export const CREATE_CLASS_MENU_PERMISSION = 65;
export const READ_ALL_CLASS_MENU_PERMISSION = 66;
export const UPDATE_CLASS_MENU_PERMISSION = 67;
export const DELETE_CLASS_MENU_PERMISSION = 68;

export const ASSIGNED_CLASS_MENU_PERMISSIONS = 69;
export const CREATE_ASSIGNED_CLASS_MENU_PERMISSION = 70;
export const READ_ASSIGNED_CLASS_MENU_PERMISSION = 71;
export const UPDATE_ASSIGNED_CLASS_MENU_PERMISSION = 72;
export const DELETE_ASSIGNED_CLASS_MENU_PERMISSION = 73;

// Leave of absence permissions
export const LOA_PERMISSIONS = 74;
export const READ_LOA_PERMISSION = 75;
export const UPDATE_LOA_PERMISSION = 76;

export const ASSIGNED_CLASS_LOA_PERMISSIONS = 77;
export const READ_ASSIGNED_CLASS_LOA_PERMISSION = 78;
export const UPDATE_ASSIGNED_CLASS_LOA_PERMISSION = 79;

// Album permissions
export const ALBUM_PERMISSIONS = 80;
export const CREATE_ALBUM_PERMISSION = 81;
export const READ_ALL_ALBUM_PERMISSION = 82;
export const UPDATE_ALBUM_PERMISSION = 83;
export const DELETE_ALBUM_PERMISSION = 84;

export const SCHOOL_ALBUM_PERMISSIONS = 85;
export const CREATE_SCHOOL_ALBUM_PERMISSION = 86;
export const READ_SCHOOL_ALBUM_PERMISSION = 87;
export const UPDATE_SCHOOL_ALBUM_PERMISSION = 88;
export const DELETE_SCHOOL_ALBUM_PERMISSION = 89;

export const ASSIGNED_CLASS_ALBUM_PERMISSIONS = 90;
export const CREATE_ASSIGNED_CLASS_ALBUM_PERMISSION = 91;
export const READ_ASSIGNED_CLASS_ALBUM_PERMISSION = 92;
export const UPDATE_ASSIGNED_CLASS_ALBUM_PERMISSION = 93;
export const DELETE_ASSIGNED_CLASS_ALBUM_PERMISSION = 94;

export const SCHOOL_ASSETS_PERMISSIONS = 95;
export const READ_SCHOOL_ASSETS_PERMISSION = 96;

// School permissions
export const SCHOOL_PERMISSIONS = 97;
export const UPDATE_SCHOOL_PERMISSION = 98;

// Post permissions
export const POST_PERMISSIONS = 99;
export const CREATE_POST_PERMISSION = 100;
export const READ_ALL_POST_PERMISSION = 101;
export const UPDATE_POST_PERMISSION = 102;
export const DELETE_POST_PERMISSION = 103;

export const SCHOOL_POST_PERMISSIONS = 104;
export const CREATE_SCHOOL_POST_PERMISSION = 105;
export const READ_SCHOOL_POST_PERMISSION = 106;
export const UPDATE_SCHOOL_POST_PERMISSION = 107;
export const DELETE_SCHOOL_POST_PERMISSION = 108;

export const ASSIGNED_CLASS_POST_PERMISSIONS = 109;
export const CREATE_ASSIGNED_CLASS_POST_PERMISSION = 110;
export const READ_ASSIGNED_CLASS_POST_PERMISSION = 111;
export const UPDATE_ASSIGNED_CLASS_POST_PERMISSION = 112;
export const DELETE_ASSIGNED_CLASS_POST_PERMISSION = 113;

// Comment permissions
export const COMMENT_PERMISSIONS = 114;
export const CREATE_COMMENT_PERMISSION = 115;
export const READ_ALL_COMMENT_PERMISSION = 116;
export const UPDATE_COMMENT_PERMISSION = 117;
export const DELETE_COMMENT_PERMISSION = 118;

export const SCHOOL_POST_COMMENT_PERMISSIONS = 119;
export const CREATE_SCHOOL_POST_COMMENT_PERMISSION = 120;
export const READ_SCHOOL_POST_COMMENT_PERMISSION = 121;
export const UPDATE_SCHOOL_POST_COMMENT_PERMISSION = 122;
export const DELETE_SCHOOL_POST_COMMENT_PERMISSION = 123;

export const ASSIGNED_CLASS_POST_COMMENT_PERMISSIONS = 124;
export const CREATE_ASSIGNED_CLASS_POST_COMMENT_PERMISSION = 125;
export const READ_ASSIGNED_CLASS_POST_COMMENT_PERMISSION = 126;
export const UPDATE_ASSIGNED_CLASS_POST_COMMENT_PERMISSION = 127;
export const DELETE_ASSIGNED_CLASS_POST_COMMENT_PERMISSION = 128;

// Notification permissions
export const NOTIFICATION_PERMISSIONS = 129;
export const CREATE_NOTIFICATION_PERMISSION = 130;
export const READ_ALL_NOTIFICATION_PERMISSION = 131;
export const UPDATE_NOTIFICATION_PERMISSION = 132;
export const DELETE_NOTIFICATION_PERMISSION = 133;

export const SCHOOL_NOTIFICATION_PERMISSIONS = 134;
export const READ_SCHOOL_NOTIFICATION_PERMISSION = 135;
export const CREATE_SCHOOL_NOTIFICATION_PERMISSION = 136;
export const UPDATE_SCHOOL_NOTIFICATION_PERMISSION = 137;

export const ASSIGNED_CLASS_NOTIFICATION_PERMISSIONS = 138;
export const READ_ASSIGNED_CLASS_NOTIFICATION_PERMISSION = 139;
export const CREATE_ASSIGNED_CLASS_NOTIFICATION_PERMISSION = 140;
export const UPDATE_ASSIGNED_CLASS_NOTIFICATION_PERMISSION = 141;

// Medical permissions
export const MEDICAL_PERMISSIONS = 142;
export const READ_MEDICAL_PERMISSION = 143;

export const ASSIGNED_CLASS_MEDICAL_PERMISSIONS = 144;
export const READ_ASSIGNED_CLASS_MEDICAL_PERMISSION = 145;
