export const CREATE_ROLE_PERMISSION = 1;
export const READ_ROLE_PERMISSION = 2;
export const UPDATE_ROLE_PERMISSION = 3;
export const DELETE_ROLE_PERMISSION = 4;

export const READ_PERMISSION_PERMISSION = 5;
export const UPDATE_PERMISSION_PERMISSION = 6;

// School year permissions
export const CREATE_SCHOOL_YEAR_PERMISSION = 7;
export const READ_ALL_SCHOOL_YEAR_PERMISSION = 8;
export const UPDATE_SCHOOL_YEAR_PERMISSION = 9;
export const DELETE_SCHOOL_YEAR_PERMISSION = 10;

// Student permissions
export const CREATE_STUDENT_PERMISSION = 11;
export const READ_ALL_STUDENT_PERMISSION = 12;
export const UPDATE_STUDENT_PERMISSION = 13;
export const DELETE_STUDENT_PERMISSION = 14;

// Parent permissions
export const CREATE_PARENT_PERMISSION = 15;
export const READ_ALL_PARENT_PERMISSION = 16;
export const UPDATE_PARENT_PERMISSION = 17;
export const DELETE_PARENT_PERMISSION = 18;

// Teacher permissions
export const CREATE_SCHOOL_FACULTY_PERMISSION = 19;
export const READ_SCHOOL_FACULTY_PERMISSION = 20;
export const UPDATE_SCHOOL_FACULTY_PERMISSION = 21;
export const DELETE_SCHOOL_FACULTY_PERMISSION = 22;

// Class permissions
export const CREATE_CLASS_PERMISSION = 23;
export const READ_ALL_CLASS_PERMISSION = 24;
export const UPDATE_CLASS_PERMISSION = 25;
export const DELETE_CLASS_PERMISSION = 26;

export const READ_ASSIGNED_CLASS_PERMISSION = 27;
export const UPDATE_ASSIGNED_CLASS_PERMISSION = 28;
export const DELETE_ASSIGNED_CLASS_PERMISSION = 29;

// Class student permissions
export const ADD_CLASS_STUDENT_PERMISSION = 30;
export const UPDATE_CLASS_STUDENT_PERMISSION = 31;
export const REMOVE_CLASS_STUDENT_PERMISSION = 32;

export const ADD_ASSIGNED_CLASS_STUDENT_PERMISSION = 33;
export const READ_ASSIGNED_CLASS_STUDENT_PERMISSION = 34;
export const UPDATE_ASSIGNED_CLASS_STUDENT_PERMISSION = 35;
export const REMOVE_ASSIGNED_CLASS_STUDENT_PERMISSION = 36;

// Class schedule permissions
export const CREATE_ASSIGNED_CLASS_SCHEDULE_PERMISSION = 37;
export const READ_ASSIGNED_CLASS_SCHEDULE_PERMISSION = 38;
export const UPDATE_ASSIGNED_CLASS_SCHEDULE_PERMISSION = 39;
export const DELETE_ASSIGNED_CLASS_SCHEDULE_PERMISSION = 40;

export const CREATE_CLASS_SCHEDULE_PERMISSION = 41;
export const READ_CLASS_SCHEDULE_PERMISSION = 42;
export const UPDATE_CLASS_SCHEDULE_PERMISSION = 43;
export const DELETE_CLASS_SCHEDULE_PERMISSION = 44;

// Assigned class menu permissions
export const CREATE_ASSIGNED_CLASS_MENU_PERMISSION = 45;
export const READ_ASSIGNED_CLASS_MENU_PERMISSION = 46;
export const UPDATE_ASSIGNED_CLASS_MENU_PERMISSION = 47;
export const DELETE_ASSIGNED_CLASS_MENU_PERMISSION = 48;

export const CREATE_CLASS_MENU_PERMISSION = 49;
export const READ_CLASS_MENU_PERMISSION = 50;
export const UPDATE_CLASS_MENU_PERMISSION = 51;
export const DELETE_CLASS_MENU_PERMISSION = 52;

// Leave of absence permissions
export const READ_ASSIGNED_CLASS_LOA_PERMISSION = 53;
export const UPDATE_ASSIGNED_CLASS_LOA_PERMISSION = 54;

export const READ_LOA_PERMISSION = 55;
export const UPDATE_LOA_PERMISSION = 56;

// Album permissions
export const CREATE_ALBUM_PERMISSION = 57;
export const READ_ALL_ALBUM_PERMISSION = 58;
export const UPDATE_ALL_ALBUM_PERMISSION = 59;
export const DELETE_ALL_ALBUM_PERMISSION = 60;

export const CREATE_SCHOOL_ALBUM_PERMISSION = 89;
export const READ_SCHOOL_ALBUM_PERMISSION = 90;
export const UPDATE_SCHOOL_ALBUM_PERMISSION = 91;
export const DELETE_SCHOOL_ALBUM_PERMISSION = 92;

export const CREATE_ASSIGNED_CLASS_ALBUM_PERMISSION = 61;
export const READ_ASSIGNED_CLASS_ALBUM_PERMISSION = 62;
export const UPDATE_ASSIGNED_CLASS_ALBUM_PERMISSION = 63;
export const DELETE_ASSIGNED_CLASS_ALBUM_PERMISSION = 64;

export const READ_SCHOOL_ASSETS_PERMISSION = 65;

// School permissions
export const UPDATE_SCHOOL_PERMISSION = 66;

// Post permissions
export const CREATE_POST_PERMISSION = 67;
export const READ_ALL_POST_PERMISSION = 68;
export const UPDATE_POST_PERMISSION = 69;
export const DELETE_POST_PERMISSION = 70;

export const CREATE_SCHOOL_POST_PERMISSION = 93;
export const READ_SCHOOL_POST_PERMISSION = 94;
export const UPDATE_SCHOOL_POST_PERMISSION = 95;
export const DELETE_SCHOOL_POST_PERMISSION = 96;

export const CREATE_ASSIGNED_CLASS_POST_PERMISSION = 71;
export const READ_ASSIGNED_CLASS_POST_PERMISSION = 72;
export const UPDATE_ASSIGNED_CLASS_POST_PERMISSION = 73;
export const DELETE_ASSIGNED_CLASS_POST_PERMISSION = 74;

// Comment permissions
export const CREATE_COMMENT_PERMISSION = 75;
export const READ_ALL_COMMENT_PERMISSION = 76;
export const UPDATE_COMMENT_PERMISSION = 77;
export const DELETE_COMMENT_PERMISSION = 78;

export const CREATE_SCHOOL_POST_COMMENT_PERMISSION = 97;
export const READ_SCHOOL_POST_COMMENT_PERMISSION = 98;
export const UPDATE_SCHOOL_POST_COMMENT_PERMISSION = 99;
export const DELETE_SCHOOL_POST_COMMENT_PERMISSION = 100;

export const CREATE_ASSIGNED_CLASS_POST_COMMENT_PERMISSION = 79;
export const READ_ASSIGNED_CLASS_POST_COMMENT_PERMISSION = 80;
export const UPDATE_ASSIGNED_CLASS_POST_COMMENT_PERMISSION = 81;
export const DELETE_ASSIGNED_CLASS_POST_COMMENT_PERMISSION = 82;

// Notifcation permissions
export const READ_SCHOOL_NOTIFICATION_PERMISSION = 83;
export const CREATE_SCHOOL_NOTIFICATION_PERMISSION = 84;
export const READ_ASSIGNED_CLASS_NOTIFICATION_PERMISSION = 85;
export const CREATE_ASSIGNED_CLASS_NOTIFICATION_PERMISSION = 86;

// Medical permissions
export const READ_MEDICAL_PERMISSION = 87;
export const READ_ASSIGNED_CLASS_MEDICAL_PERMISSION = 88;
